parameters:
    secret: HkfjCKCY0dqUBoh8RAAQAJK51kned19P

    google_client_id: test.apps.googleusercontent.com
    google_client_secret: test-l3gtpVCUph-
    twitter_client_id: testg1xr6EqAd3AbD
    twitter_client_secret: test4SSCFMcKo6f29EX3PmbjT235
    facebook_client_id: test826303848
    facebook_client_secret: test5e31e7d5ee6321

    # Stripe keys
    stripe_public_key: pk_test_GX625rcwtest
    stripe_secret_key: sk_test_NR5vdMetest
    payment:
        currency: CAD
        decimal: true
        

    # app_encryption_secret: Q22XJeVybZg3jotest
    app_encryption_secret: testf07a6b1d819619408077fb370a93ac3dcb150e529e7c77796d53fe696af6bf52ca298835c59e093831a1811aa7a2df6d


    # customize the full path to external executables
    # normally they are auto-detected by `which program` or auto-discovered in the configured path in
    # System Settings -> General -> Additional $PATH variable
    # but in general it's a good idea to have your programs in your $PATH environment variable (system wide)

    #pimcore_executable_composer: php /opt/vendor/bin/composer.phar
    #pimcore_executable_html2text: /usr/local/html2text/bin/html2text
    #pimcore_executable_soffice: /opt/libreoffice/bin/soffice
    #pimcore_executable_gs: /opt/ghostscript/bin/gs
    #pimcore_executable_pdftotext: /opt/tools/pdftotext
    #pimcore_executable_xvfb-run: /opt/tools/xvfb-run
    #pimcore_executable_pngcrush: /opt/tools/pngcrush
    #pimcore_executable_zopflipng: /opt/tools/zopflipng
    #pimcore_executable_pngout: /opt/tools/pngout
    #pimcore_executable_advpng: /opt/tools/advpng
    #pimcore_executable_cjpeg: /opt/tools/cjpeg
    #pimcore_executable_jpegoptim: /opt/tools/jpegoptim
    #pimcore_executable_php: /usr/local/custom-php/bin/php
    #pimcore_executable_nice: /opt/tools/nice
    #pimcore_executable_nohup: /opt/tools/nohup
    #pimcore_executable_ffmpeg: /opt/tools/ffmpeg
    #pimcore_executable_exiftool: /opt/tools/exiftool

